version: '3.8'

services:
  flights-prediction:
    build: .
    container_name: flights-prices-prediction
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"  
      - "8000:8000" 
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: >
      sh -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"
    
  api:
    build: .
    container_name: flights-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
    command: python api.py  

volumes:
  data:
  notebooks: